version : '3'

services:
        db:
                image: postgres
                restart: always
                ports:
                        - 5432:5432
                volumes:
                        - postgres_storage:/var/lib/postgresql/data
                environment:
                        POSTGRES_PASSWORD: sudo_root
                        POSTGRES_USER: root
                        POSTGRES_DB: mydb


        blog:
                restart: always
                build: ./blogapp1
                command: python manage.py runserver 0.0.0.0:8000
                volumes:
                        - ./blogapp1:/code
                ports:
                        - 8000:8000
                depends_on: 
                        - db

volumes:
        postgres_storage:
